### PR TITLE
Feature

### PR DESCRIPTION
**Pull request by alissonperes**

### CODE REVIEW

**Comment by alissonperes** [comment]
@Forison  thanks for the review. The first section after the navbar was showing 3 articles because of the screen size. We found that there is a media query to display 3 in larger displays and 4 (in 2 rows) in smaller screens. We added the media query to display the info that way and so far so good.

Thanks for the heads up. :+1:

**Comment by alissonperes** [comment]
@whiz25 the article section has a media query that with screens 1900 or higher the page displays two articles per row with tow rows, with screens higher it displays three articles in one row.

the horizontal scroll was already fixed but not replicated on githack production (only development)

**Comment by whiz25** [comment]
@alissonperes okay re-submit and I will approve it.

**Comment by alissonperes** [comment]
> @alissonperes okay re-submit and I will approve it.

Already re-submited, thanks

**Pull request merged**
